---
generic-service:
  nameOverride: hmpps-audit-poc-ui
  serviceAccountName: hmpps-audit-poc
  productId: "DPS018"

  replicaCount: 2

  image:
    repository: ghcr.io/ministryofjustice/hmpps-audit-poc-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-audit-poc-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-audit-poc-ui"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-audit-poc-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-audit-poc-ui-auth-code:
      AUTH_CODE_CLIENT_ID: "AUTH_CODE_CLIENT_ID"
      AUTH_CODE_CLIENT_SECRET: "AUTH_CODE_CLIENT_SECRET"
    hmpps-audit-poc-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: "CLIENT_CREDS_CLIENT_ID"
      CLIENT_CREDS_CLIENT_SECRET: "CLIENT_CREDS_CLIENT_SECRET"
    hmpps-audit-poc-ui-session-secret:
      SESSION_SECRET: "SESSION_SECRET"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-audit-poc-ui
