---
# Per environment values which override defaults in hmpps-audit-poc-ui/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true
    startup: '46 6 * * 1-5' # Start at 6.45am UTC Monday-Friday
    shutdown: '24 21 * * 1-5' # Stop at 9.24pm UTC Monday-Friday

  ingress:
    host: audit-poc-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://audit-poc-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  businessHoursOnly: true

